services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ../..:/app:cached
    working_dir: /app
    command: sleep infinity
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://mongodb:27017/trustroots-dev

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    volumes:
      - mongodb-data:/data/db
      - ../../nr-bridge/trustroots_docs/trustroots-dev.archive:/archive/trustroots-dev.archive:ro
    ports:
      - "27017:27017"
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb-data:
