services:
  strfry-nostr-relay:
    image: ghcr.io/trustroots/strfry:master
    container_name: strfry

    volumes:
      - ./strfry.conf:/etc/strfry.conf
      - ./strfry-db:/app/strfry-db
      - ./strfry-plugins:/app/strfry-plugins
    ports:
      - "7777:7777"
